import {StyleSheet} from 'react-native';
import { Fonts } from '../../../globalStyles';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#000',
    },
    camera: {
      flex: 1,
    },
    header: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 20,
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      zIndex: 10,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(208, 208, 208, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    backIcon: {
      width: 20,
      height: 20,
      tintColor: '#FFFFFF',
    },
    headerTitle: {
      fontSize: 24,
      color: '#FFFFFF',
      fontFamily: Fonts.PFbold,
    },
    torchButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(208, 208, 208, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    torchIcon: {
      width: 20,
      height: 20,
      tintColor: '#FFFFFF',
    },
    overlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    scanArea: {
      width: 250,
      height: 250,
      borderRadius: 16,
      backgroundColor: 'transparent',
      overflow: 'hidden',
      justifyContent: 'center',
      alignItems: 'center',
    },
    corner: {
      position: 'absolute',
      width: 24,
      height: 24,
      borderColor: '#FFFFFF',
    },
    topLeftCorner: {
      top: 0,
      left: 0,
      borderTopWidth: 3,
      borderLeftWidth: 3,
      borderTopLeftRadius: 16,
    },
    topRightCorner: {
      top: 0,
      right: 0,
      borderTopWidth: 3,
      borderRightWidth: 3,
      borderTopRightRadius: 16,
    },
    bottomLeftCorner: {
      bottom: 0,
      left: 0,
      borderBottomWidth: 3,
      borderLeftWidth: 3,
      borderBottomLeftRadius: 16,
    },
    bottomRightCorner: {
      bottom: 0,
      right: 0,
      borderBottomWidth: 3,
      borderRightWidth: 3,
      borderBottomRightRadius: 16,
    },
    instructionText: {
      marginTop: 32,
      color: '#FFFFFF',
      fontSize: 20,
      textAlign: 'center',
      paddingHorizontal: 40,
      fontFamily: Fonts.PFregular,
    },
    processingContainer: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    processingIndicator: {
      backgroundColor: '#5271FF',
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 12,
    },
    processingText: {
      color: '#FFFFFF',
      fontSize: 20,
      fontFamily: Fonts.PFregular,
    },
    permissionContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#F5F8FF',
      padding: 24,
    },
    permissionIcon: {
      width: 80,
      height: 80,
      tintColor: '#95A1C3',
      marginBottom: 24,
    },
    permissionTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 12,
      textAlign: 'center',
    },
    permissionText: {
      fontSize: 16,
      color: '#95A1C3',
      textAlign: 'center',
      marginBottom: 32,
    },
  });
