import {StyleSheet} from 'react-native';
import {Colors, Fonts, Responsive, BorderRadius} from '../../../globalStyles';

const {wp, hp, fontSize} = Responsive;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  pageTitle: {
    fontSize: fontSize.xl,
    fontFamily: Fonts.PFbold,
    color: Colors.text,
    marginHorizontal: wp(4),
    marginTop: hp(2),
    marginBottom: hp(1),
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.round,
    padding: wp(1),
    paddingHorizontal: wp(3),
    margin: wp(4),
    marginTop: hp(3),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  searchInput: {
    flex: 1,
    padding: wp(2.5),
    fontSize: fontSize.md,
    color: Colors.text,
    fontFamily: Fonts.PFregular,
    backgroundColor: 'transparent',
  },
  filterButton: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(6),
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    margin: wp(1),
  },
  filterIcon: {
    fontSize: fontSize.lg,
    color: Colors.white,
  },
  courseStatus: {
    fontSize: 12,
    marginLeft: 4,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(4),
  },
  emptyText: {
    fontSize: fontSize.md,
    color: Colors.textLight,
    marginBottom: hp(2.5),
    fontFamily: Fonts.PFmedium,
    textAlign: 'center',
  },
  addButton: {
    backgroundColor: Colors.primary,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(6),
    borderRadius: BorderRadius.md,
    marginTop: hp(2),
  },
  addButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  floatingAddButton: {
    position: 'absolute',
    bottom: hp(4),
    right: wp(5),
    width: wp(15),
    height: wp(15),
    backgroundColor: Colors.primary,
    borderRadius: wp(7.5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  floatingAddButtonText: {
    color: Colors.white,
    fontSize: fontSize.xxl,
    fontFamily: Fonts.PFbold,
  },
  listContent: {
    // padding: wp(0),
    paddingHorizontal: wp(4),
  },
  studentItem: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    padding: wp(3),
    borderRadius: BorderRadius.lg,
    marginBottom: hp(1),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  studentItemContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  studentAvatar: {
    width: wp(12),
    height: wp(12),
    borderRadius: wp(6),
    backgroundColor: '#8AEC7F',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(3),
  },
  studentAvatarText: {
    fontSize: fontSize.lg,
    color: Colors.primary,
    fontFamily: Fonts.PFbold,
  },
  studentMainInfo: {
    flex: 1,
  },
  studentName: {
    fontSize: fontSize.lg,
    color: Colors.text,
    fontFamily: Fonts.PFbold,
    marginBottom: hp(0.5),
  },
  studentCourse: {
    fontSize: fontSize.sm,
    color: Colors.textLight,
    fontFamily: Fonts.PFregular,
  },
  studentGender: {
    fontSize: fontSize.sm,
    color: Colors.textLight,
    fontFamily: Fonts.PFregular,
  },
  swipeAction: {
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(20),
    height: '100%',
  },
  swipeEdit: {
    backgroundColor: Colors.primary,
  },
  swipeDelete: {
    backgroundColor: Colors.error,
  },
  swipeActionText: {
    color: Colors.white,
    fontSize: fontSize.sm,
    fontFamily: Fonts.PFmedium,
  },
  statusIndicator: {
    width: wp(3),
    height: wp(3),
    borderRadius: wp(1.5),
    marginRight: wp(2),
  },
  statusActive: {
    backgroundColor: Colors.success,
  },
  statusInactive: {
    backgroundColor: Colors.error,
  },
  disabledItem: {
    opacity: 0.8,
    borderColor: Colors.error,
  },
  avatar: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    backgroundColor: Colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(4),
  },
  avatarText: {
    fontSize: fontSize.lg,
    color: Colors.text,
    fontFamily: Fonts.PFbold,
  },
  studentDetails: {
    flex: 1,
  },
  studentNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp(1),
  },
  statusDot: {
    width: wp(3),
    height: wp(3),
    borderRadius: wp(1.5),
    marginRight: wp(2),
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.background,
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.5),
    borderRadius: BorderRadius.md,
  },
  studentInfo: {
    fontSize: fontSize.sm,
    color: Colors.textLight,
    fontFamily: Fonts.PFregular,
    marginBottom: hp(0.5),
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: wp(2),
  },
  editButton: {
    padding: wp(2),
    marginRight: wp(2),
    backgroundColor: Colors.background,
    borderRadius: BorderRadius.md,
  },
  deleteButton: {
    padding: wp(2),
    backgroundColor: Colors.error + '15',
    borderRadius: BorderRadius.md,
  },
  editIcon: {
    fontSize: fontSize.lg,
    color: Colors.primary,
  },
  deleteIcon: {
    fontSize: fontSize.lg,
    color: Colors.error,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.64)',
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    padding: wp(5),
    width: wp(90),
    maxHeight: hp(80),
    bottom: hp(3),
  },
  modalHandle: {
    width: wp(10),
    height: wp(1),
    backgroundColor: Colors.border,
    borderRadius: wp(0.5),
    alignSelf: 'center',
    marginBottom: hp(2),
  },
  modalTitle: {
    fontSize: fontSize.xl,
    color: Colors.text,
    marginBottom: hp(2.5),
    fontFamily: Fonts.PFbold,
    textAlign: 'center',
  },
  closeButton: {
    padding: wp(2),
    position: 'absolute',
    right: wp(4),
    top: hp(4),
  },
  closeButtonText: {
    fontSize: fontSize.xxl,
    color: Colors.textLight,
    fontFamily: Fonts.PFregular,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: BorderRadius.md,
    padding: wp(3),
    marginBottom: hp(2),
    fontSize: fontSize.md,
    color: Colors.text,
    fontFamily: Fonts.PFregular,
    backgroundColor: Colors.white,
  },
  filterLabel: {
    fontSize: fontSize.md,
    color: Colors.text,
    marginBottom: hp(1),
    fontFamily: Fonts.PFmedium,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(2),
  },
  cancelButton: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(5),
    borderRadius: BorderRadius.md,
    flex: 1,
    marginRight: wp(2),
    alignItems: 'center',
  },
  cancelButtonExport: {
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
    marginBottom: hp(2),
    alignItems: 'center',
  },
  cancelButtonText: {
    color: Colors.text,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  deleteButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  saveButton: {
    backgroundColor: Colors.primary,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(5),
    borderRadius: BorderRadius.md,
    flex: 1,
    alignItems: 'center',
  },
  icon: {
    height: 24,
    width: 24,
  },
  iconBlack: {
    tintColor: 'black',
  },
  iconWhite: {
    tintColor: 'white',
  },
  saveButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  submitButton: {
    backgroundColor: Colors.primary,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(5),
    borderRadius: BorderRadius.md,
    flex: 1,
    alignItems: 'center',
  },
  submitButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  clearButton: {
    backgroundColor: Colors.error,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(5),
    borderRadius: BorderRadius.md,
    flex: 1,
    marginRight: wp(2),
    alignItems: 'center',
  },
  clearButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  statusOptions: {
    flexDirection: 'row',
    marginBottom: hp(2),
  },
  statusOption: {
    flex: 1,
    paddingVertical: hp(1.5),
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 0.8,
    marginRight: wp(2),
    borderRadius: BorderRadius.md,
  },
  statusOptionSelected: {
    backgroundColor: Colors.primary,
  },
  statusOptionText: {
    fontSize: fontSize.md,
    color: Colors.textLight,
    fontFamily: Fonts.PFmedium,
  },
  statusOptionTextSelected: {
    color: Colors.white,
  },
  filterSection: {
    marginBottom: hp(2),
  },
  sectionTitle: {
    fontSize: fontSize.lg,
    color: Colors.text,
    fontFamily: Fonts.PFbold,
    marginBottom: hp(1),
  },
  statContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: hp(2),
    marginHorizontal: wp(4),
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.md,
    padding: wp(4),
    marginHorizontal: wp(1),
    alignItems: 'center',
  },
  statValue: {
    fontSize: fontSize.xl,
    color: Colors.text,
    fontFamily: Fonts.PFbold,
  },
  statLabel: {
    fontSize: fontSize.sm,
    color: Colors.textLight,
    fontFamily: Fonts.PFmedium,
    marginTop: hp(0.5),
  },
  emptyIllustration: {
    width: wp(40),
    height: wp(40),
    marginBottom: hp(2),
  },
  methodButton: {
    backgroundColor: Colors.primary,
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
    borderRadius: BorderRadius.md,
    marginBottom: hp(2),
    alignItems: 'center',
  },
  methodButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  filterSectionTitle: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFbold,
    color: Colors.text,
    marginBottom: hp(1),
    marginTop: hp(2),
  },
  filterOption: {
    padding: wp(3),
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.white,
    marginBottom: hp(1.25),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  filterOptionSelected: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  filterOptionText: {
    fontSize: fontSize.md,
    color: Colors.text,
    fontFamily: Fonts.PFregular,
  },
  filterOptionTextSelected: {
    color: Colors.white,
  },
  exportFormatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(2),
    marginTop: hp(1),
  },
  exportFormatCard: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    marginHorizontal: wp(1),
    padding: wp(4),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  exportFormatLabel: {
    color: Colors.text,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
    marginTop: hp(1),
    marginBottom: hp(1),
  },
  exportFormatActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  exportActionButton: {
    padding: wp(2),
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary,
    marginHorizontal: wp(1),
  },
  bottomSheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    padding: wp(5),
  },
  bottomSheetHandle: {
    width: wp(10),
    height: wp(1),
    backgroundColor: Colors.border,
    borderRadius: wp(0.5),
    alignSelf: 'center',
    marginBottom: hp(2),
  },
  bottomSheetTitle: {
    fontSize: fontSize.xl,
    color: Colors.text,
    fontFamily: Fonts.PFbold,
    marginBottom: hp(2),
  },
  detailRow: {
    flexDirection: 'row',
    marginBottom: hp(1.5),
    paddingVertical: hp(0.5),
  },
  detailLabel: {
    width: wp(30),
    fontSize: fontSize.md,
    color: Colors.textLight,
    fontFamily: Fonts.PFmedium,
  },
  detailValue: {
    flex: 1,
    fontSize: fontSize.md,
    color: Colors.text,
    fontFamily: Fonts.PFregular,
  },
  bottomSheetActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(3),
    paddingTop: hp(2),
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  bottomSheetButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(1.5),
    borderRadius: BorderRadius.md,
    marginHorizontal: wp(1),
  },
  bottomSheetButtonText: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
    marginLeft: wp(2),
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(3),
    paddingTop: hp(2),
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  modalButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(1.5),
    borderRadius: BorderRadius.md,
    marginHorizontal: wp(1),
  },
  modalButtonText: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
    marginLeft: wp(2),
  },
});
