import {StyleSheet} from 'react-native';
import {Colors, Fonts, Responsive, BorderRadius} from '../../../globalStyles';

const {wp, hp, fontSize} = Responsive;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  pageTitle: {
    fontSize: fontSize.xl,
    fontFamily: Fonts.PFbold,
    color: Colors.text,
    marginHorizontal: wp(4),
    marginTop: hp(2),
    marginBottom: hp(2),
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.round,
    padding: wp(1),
    paddingHorizontal: wp(3),
    margin: wp(4),
    marginTop: hp(3),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  searchInput: {
    flex: 1,
    padding: wp(2.5),
    fontSize: fontSize.md,
    color: Colors.text,
    fontFamily: Fonts.PFregular,
    backgroundColor: 'transparent',
  },
  filterButton: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    margin: wp(1),
  },
  filterIcon: {
    fontSize: fontSize.lg,
    color: Colors.white,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(4),
  },
  emptyText: {
    fontSize: fontSize.md,
    color: Colors.textLight,
    marginBottom: hp(2.5),
    fontFamily: Fonts.PFmedium,
  },
  addButton: {
    backgroundColor: Colors.primary,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(6),
    borderRadius: BorderRadius.md,
    marginTop: hp(2),
  },
  addButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  floatingAddButton: {
    position: 'absolute',
    bottom: hp(4),
    right: wp(5),
    width: wp(15),
    height: wp(15),
    backgroundColor: Colors.primary,
    borderRadius: wp(7.5),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: `${Colors.primary}80`,
  },
  floatingAddButtonText: {
    color: Colors.white,
    fontSize: fontSize.xxl,
    fontFamily: Fonts.PFbold,
  },
  listContent: {
    paddingHorizontal: wp(4),
  },
  courseItem: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    padding: wp(3),
    borderRadius: BorderRadius.lg,
    marginBottom: hp(1),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  disabledItem: {
    borderLeftColor: '#EF4444',
    opacity: 0.8,
  },
  avatar: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    backgroundColor: Colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(4),
  },
  avatarText: {
    fontSize: fontSize.lg,
    color: Colors.text,
    fontFamily: Fonts.PFbold,
  },
  courseItemContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  courseInfo: {
    flex: 1,
  },
  courseName: {
    fontSize: fontSize.lg,
    color: Colors.text,
    marginBottom: hp(0.5),
    fontFamily: Fonts.PFbold,
  },
  courseNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusDot: {
    width: wp(3),
    height: wp(3),
    borderRadius: wp(1.5),
    marginRight: wp(2),
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(0.5),
  },
  courseDetails: {
    fontSize: fontSize.sm,
    color: Colors.textLight,
    fontFamily: Fonts.PFregular,
  },
  statusIndicator: {
    width: wp(3),
    height: wp(3),
    borderRadius: wp(1.5),
    marginRight: wp(2),
  },
  statusText: {
    fontSize: fontSize.sm,
    color: Colors.textLight,
    fontFamily: Fonts.PFregular,
  },
  courseDuration: {
    fontSize: fontSize.sm,
    color: Colors.textLight,
    fontFamily: Fonts.PFregular,
    marginBottom: hp(0.5),
  },
  statusActive: {
    backgroundColor: Colors.success,
  },
  statusInactive: {
    backgroundColor: Colors.error,
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editButton: {
    padding: wp(2),
    marginRight: wp(2),
  },
  deleteButton: {
    padding: wp(2),
  },
  editIcon: {
    fontSize: fontSize.lg,
    color: Colors.primary,
  },
  deleteIcon: {
    fontSize: fontSize.lg,
    color: Colors.error,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.64)',
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    padding: wp(5),
    width: wp(90),
    maxHeight: hp(80),
    bottom: hp(3),
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: Colors.border,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: hp(2),
  },
  modalTitle: {
    fontSize: fontSize.xl,
    color: Colors.text,
    marginBottom: hp(2.5),
    fontFamily: Fonts.PFbold,
    textAlign: 'center',
  },
  detailRow: {
    flexDirection: 'row',
    paddingVertical: hp(1),
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  detailLabel: {
    flex: 1,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
    color: Colors.text,
  },
  detailValue: {
    flex: 2,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFregular,
    color: Colors.text,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: BorderRadius.md,
    padding: wp(3),
    marginBottom: hp(2),
    fontSize: fontSize.md,
    color: Colors.text,
    fontFamily: Fonts.PFregular,
  },
  filterSectionTitle: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFbold,
    color: Colors.text,
    marginBottom: hp(1),
    marginTop: hp(1),
  },
  statusOptions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(3),
  },
  statusOption: {
    flex: 1,
    padding: wp(3),
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.background,
    alignItems: 'center',
    marginHorizontal: wp(1),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  statusOptionSelected: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  statusOptionText: {
    color: Colors.text,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  statusOptionTextSelected: {
    color: Colors.white,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(2),
  },
  cancelButton: {
    padding: wp(3),
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.background,
    flex: 1,
    marginRight: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  cancelButtonExport: {
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
    marginBottom: hp(2),
    alignItems: 'center',
  },
  saveButton: {
    padding: wp(3),
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary,
    flex: 1,
    marginLeft: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  cancelButtonText: {
    color: Colors.text,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  saveButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  deleteButtonText: {
    color: Colors.error,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  filterOption: {
    padding: wp(3),
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.white,
    marginBottom: hp(1.25),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  filterOptionText: {
    fontSize: fontSize.md,
    color: Colors.text,
    fontFamily: Fonts.PFregular,
  },
  filterOptionSelected: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  filterOptionTextSelected: {
    color: Colors.white,
  },
  markAllButton: {
    backgroundColor: Colors.primary,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(4),
    borderRadius: BorderRadius.md,
    marginTop: hp(2),
    alignSelf: 'center',
  },
  markAllButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  footerSpace: {
    height: hp(10),
  },
  methodButton: {
    backgroundColor: Colors.primary,
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
    borderRadius: BorderRadius.md,
    marginBottom: hp(2),
    alignItems: 'center',
  },
  methodButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  methodButtonIcon: {
    width: wp(5),
    height: wp(5),
    marginLeft: wp(2),
    tintColor: Colors.white,
  },
  exportFormatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(2),
    marginTop: hp(1),
  },
  exportFormatCard: {
    flex: 1,
    backgroundColor: Colors.accent,
    borderRadius: BorderRadius.md,
    marginHorizontal: wp(1),
    paddingVertical: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  exportFormatCardActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  exportFormatLabel: {
    color: Colors.text,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
    marginRight: wp(2),
  },
  exportFormatLabelActive: {
    color: Colors.white,
  },
  exportDownloadIconBtn: {
    padding: wp(1.5),
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.primary,
    marginLeft: wp(1),
  },
  exportDownloadIcon: {
    width: wp(6),
    height: wp(6),
    tintColor: Colors.white,
  },
  exportFormatCardStatic: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.md,
    marginHorizontal: wp(1),
    paddingVertical: hp(2),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: hp(1.5),
  },
  exportFormatLabelStatic: {
    color: Colors.text,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
    marginLeft: wp(2),
  },
  exportFormatActions: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: wp(2),
  },
  exportShareIconBtn: {
    padding: wp(1.5),
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.primary,
    marginLeft: wp(1),
  },
  exportShareIcon: {
    width: wp(6),
    height: wp(6),
    tintColor: Colors.white,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(3),
    gap: wp(2),
  },
  modalButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: wp(3),
    borderRadius: BorderRadius.md,
    gap: wp(2),
  },
  modalButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  icon: {
    height: 24,
    width: 24,
  },
  iconBlack: {
    tintColor: 'black',
  },
  iconWhite: {
    tintColor: 'white',
  },
  detailsModalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius.lg,
    borderTopRightRadius: BorderRadius.lg,
    padding: wp(5),
    width: wp(100),
    maxHeight: hp(80),
  },
  detailsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  detailsTitle: {
    fontSize: fontSize.xl,
    color: Colors.text,
    marginBottom: hp(2.5),
    fontFamily: Fonts.PFbold,
    textAlign: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: hp(2),
    right: wp(4),
    padding: wp(2),
  },
  closeButtonText: {
    fontSize: fontSize.xl,
    color: Colors.text,
    fontFamily: Fonts.PFmedium,
  },
  detailsBody: {
    marginBottom: hp(2),
  },
  detailsActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(2),
  },
  actionButton: {
    flex: 1,
    paddingVertical: hp(1.5),
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    marginHorizontal: wp(2),
  },
  actionButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
});
