// src/screens/admin/Attendance/styles.tsx
import {StyleSheet} from 'react-native';
import {
  Colors,
  Fonts,
  Responsive,
  BorderRadius,
  Spacing,
} from '../../../globalStyles';

const {wp, hp, fontSize} = Responsive;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    padding: hp(2),
  },
  headerTitle: {
    color: Colors.white,
    fontSize: fontSize.xl,
    fontFamily: Fonts.PFbold,
    marginBottom: hp(2),
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.round,
    padding: wp(1),
    paddingHorizontal: wp(3),
    margin: wp(4),
    marginTop: hp(3),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  searchInput: {
    flex: 1,
    padding: wp(2.5),
    fontSize: fontSize.md,
    color: Colors.text,
    fontFamily: Fonts.PFregular,
    backgroundColor: 'transparent',
  },
  filterButton: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    margin: wp(1),
  },
  filterIcon: {
    fontSize: fontSize.lg,
    color: Colors.white,
  },
  icon: {
    height: 24,
    width: 24,
  },
  iconBlack: {
    tintColor: 'black',
  },
  iconWhite: {
    tintColor: 'white',
  },
  dateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: hp(2),
    paddingHorizontal: wp(4),
  },
  datePickerButton: {
    backgroundColor: Colors.white,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(3),
    borderRadius: BorderRadius.md,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  filterLabel: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
    color: Colors.text,
  },
  calendarIcon: {
    fontSize: fontSize.lg,
    color: Colors.primary,
    marginRight: wp(2),
  },
  listContent: {
    padding: wp(4),
  },
  studentItem: {
    backgroundColor: Colors.white,
    padding: wp(4),
    marginBottom: hp(2),
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
  },
  studentInfo: {
    fontSize: fontSize.sm,
    color: Colors.textLight,
    fontFamily: Fonts.PFregular,
    marginBottom: hp(0.5),
  },
  studentName: {
    fontSize: fontSize.lg,
    color: Colors.text,
    fontFamily: Fonts.PFmedium,
    marginBottom: hp(1),
  },
  presentBadge: {
    position: 'absolute',
    top: wp(2),
    right: wp(2),
    backgroundColor: Colors.success,
    paddingVertical: hp(0.5),
    paddingHorizontal: wp(2),
    borderRadius: BorderRadius.sm,
  },
  presentText: {
    color: Colors.white,
    fontSize: fontSize.xs,
    fontFamily: Fonts.PFbold,
  },
  absentBadge: {
    position: 'absolute',
    top: wp(2),
    right: wp(2),
    backgroundColor: Colors.error,
    paddingVertical: hp(0.5),
    paddingHorizontal: wp(2),
    borderRadius: BorderRadius.sm,
  },
  absentText: {
    color: Colors.white,
    fontSize: fontSize.xs,
    fontFamily: Fonts.PFbold,
  },
  notmarkBadge: {
    position: 'absolute',
    top: wp(2),
    right: wp(2),
    backgroundColor: Colors.warning,
    paddingVertical: hp(0.5),
    paddingHorizontal: wp(2),
    borderRadius: BorderRadius.sm,
  },
  notmarkText: {
    color: Colors.white,
    fontSize: fontSize.xs,
    fontFamily: Fonts.PFbold,
  },
  detailRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  detailsContainer: {
    flex: 1,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: '45%',
    marginBottom: hp(1),
  },
  detailIcon: {
    fontSize: fontSize.md,
    color: Colors.primary,
    marginRight: wp(1),
    width: wp(5),
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(6),
  },
  emptyText: {
    fontSize: fontSize.md,
    color: Colors.textLight,
    textAlign: 'center',
    fontFamily: Fonts.PFmedium,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    padding: wp(5),
    width: wp(90),
    maxHeight: hp(80),
    bottom: hp(3),
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: Colors.border,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: hp(2),
  },
  modalTitle: {
    fontSize: fontSize.xl,
    fontFamily: Fonts.PFbold,
    color: Colors.text,
    marginBottom: hp(3),
    textAlign: 'center',
  },
  filterStudents: {
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 15,
  },
  filterSectionTitle: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFbold,
    color: Colors.text,
    marginBottom: hp(1),
    marginTop: hp(2),
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: BorderRadius.md,
    padding: wp(3),
    marginBottom: hp(2),
    fontSize: fontSize.md,
    color: Colors.text,
    fontFamily: Fonts.PFregular,
    backgroundColor: Colors.white,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(3),
  },
  cancelButton: {
    padding: wp(4),
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.background,
    flex: 1,
    marginRight: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  saveButton: {
    padding: wp(3),
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary,
    flex: 1,
    marginLeft: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearButton: {
    padding: wp(3),
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.background,
    flex: 1,
    marginLeft: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.error,
  },
  cancelButtonText: {
    color: Colors.text,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  saveButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  clearButtonText: {
    color: Colors.error,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  floatingAddButton: {
    position: 'absolute',
    bottom: hp(4),
    right: wp(5),
    width: wp(15),
    height: wp(15),
    backgroundColor: Colors.primary,
    borderRadius: wp(7.5),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: `${Colors.primary}80`,
  },
  floatingAddButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFbold,
  },
  qrContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgb(254, 254, 254)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(5),
    zIndex: 1000,
  },
  qrCloseButton: {
    backgroundColor: 'black',
    //   position: 'absolute',
    top: hp(4),
    //   right: wp(4),
    borderRadius: BorderRadius.md,
    padding: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    width: '50%',
  },
  qrCloseIcon: {
    fontSize: fontSize.xl,
    color: Colors.text,
  },
  attendanceCountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
    paddingVertical: hp(1),
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  attendanceCountText: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
    color: Colors.text,
  },
  attendanceCountNumber: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFbold,
    color: Colors.primary,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.border,
    marginVertical: hp(1),
  },
  markAllButton: {
    backgroundColor: Colors.primary,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(4),
    borderRadius: BorderRadius.md,
    marginTop: hp(2),
    alignSelf: 'center',
  },
  markAllButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: wp(3),
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: BorderRadius.md,
    marginBottom: hp(2),
    backgroundColor: Colors.white,
  },
  checkboxLabel: {
    flex: 1,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFregular,
    color: Colors.text,
  },
  checkbox: {
    width: wp(6),
    height: wp(6),
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: wp(1.5),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
  },
  checkboxInner: {
    width: wp(3),
    height: wp(3),
    borderRadius: wp(0.75),
    backgroundColor: Colors.primary,
  },
  manualMarkingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.white,
    padding: wp(4),
    zIndex: 1000,
  },
  manualMarkingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(3),
    paddingBottom: hp(2),
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(3),
  },
  cancelButtonAdd: {
    flex: 0.48,
    marginLeft: 8,
  },
  markAttendanceSection: {
    marginBottom: 15,
    height: 48,
    backgroundColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
  },
  cancelButtonColor: {
    backgroundColor: 'white',
    borderWidth: 0.8,
    borderColor: 'darkgray',
  },
  crossStyle: {
    fontSize: 20,
    color: 'red',
  },
  saveButtonAdd: {
    flex: 0.48,
  },
  holidayButton: {
    backgroundColor: Colors.primary,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(3),
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: wp(2),
  },
  holidayButtonText: {
    color: Colors.white,
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
  },
  weekViewContainer: {
    width: '100%',
  },
  weekDaysContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(2.5),
    width: '100%',
  },
  dayButton: {
    padding: wp(2),
    margin: wp(0.5),
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    flex: 1,
  },
  dayButtonSelected: {
    backgroundColor: Colors.primary,
  },
  dayButtonDisabled: {
    backgroundColor: '#e0e0e0',
    opacity: 0.5,
  },
  dayButtonDefault: {
    backgroundColor: '#f0f0f0',
  },
  dayText: {
    fontSize: fontSize.xs,
    fontFamily: Fonts.PFregular,
  },
  dayNumber: {
    fontSize: fontSize.sm,
    fontFamily: Fonts.PFmedium,
  },
  dayTextSelected: {
    color: Colors.white,
    fontWeight: 'bold',
  },
  dayTextDisabled: {
    color: '#888',
  },
  dayTextDefault: {
    color: Colors.text,
  },
  expandButton: {
    alignItems: 'flex-end',
    height: 12,
    marginTop: 4,
  },
  loadingModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  loadingModalContent: {
    backgroundColor: 'white',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
  },
  weekViewWrapper: {
    marginVertical: hp(1),
  },
  weekViewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(2.5),
  },
  weekViewTitle: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFmedium,
    color: Colors.text,
  },
  weekViewSubtitle: {
    fontSize: fontSize.sm,
    fontFamily: Fonts.PFregular,
    color: Colors.textLight,
  },
  weekViewContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(1),
  },
  weekViewDay: {
    alignItems: 'center',
    flex: 1,
  },
  weekViewDayText: {
    fontSize: fontSize.xs,
    fontFamily: Fonts.PFregular,
    color: Colors.textLight,
    marginBottom: hp(0.5),
  },
  weekViewDayNumber: {
    fontSize: fontSize.sm,
    fontFamily: Fonts.PFmedium,
    color: Colors.text,
  },
  weekViewDaySelected: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.md,
    padding: wp(1),
  },
  weekViewDaySelectedText: {
    color: Colors.white,
  },
  weekViewDayDisabled: {
    opacity: 0.5,
  },
  weekViewDayDisabledText: {
    color: Colors.textLight,
  },
  customHeader: {
    fontSize: 32,
    fontWeight: '600',
    color: Colors.text,
    textAlign: 'center',
    fontFamily: Fonts.PFbold,
    marginVertical: Spacing.m,
  },
  calendarDay: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
  },
  calendarDayWeekend: {
    opacity: 0.5,
  },
  calendarDayDisabled: {
    opacity: 0.3,
  },
  calendarDayText: {
    fontSize: fontSize.sm,
    fontFamily: Fonts.PFregular,
    color: Colors.text,
  },
  calendarDayTextWeekend: {
    color: Colors.error,
    opacity: 0.5,
  },
  calendarDayTextDisabled: {
    color: Colors.textLight,
  },
  calendarDayToday: {
    backgroundColor: Colors.primary,
    borderRadius: 16,
  },
  calendarDayTextToday: {
    color: Colors.white,
    fontFamily: Fonts.PFmedium,
  },
  calendarDayHoliday: {
    backgroundColor: '#FFE5E5',
    borderRadius: 16,
  },
  calendarDayTextHoliday: {
    color: '#FF6B6B',
    fontFamily: Fonts.PFmedium,
  },
  holidayDetailsContainer: {
    padding: wp(4),
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.md,
    marginBottom: hp(2),
  },
  holidayDate: {
    fontSize: fontSize.lg,
    fontFamily: Fonts.PFbold,
    color: Colors.text,
    marginBottom: hp(1),
  },
  holidayDescription: {
    fontSize: fontSize.md,
    fontFamily: Fonts.PFregular,
    color: Colors.text,
    lineHeight: 24,
  },
  courseItem: {
  backgroundColor: 'white',
  borderRadius: 12,
  padding: 16,
  marginBottom: 12,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  shadowColor: '#000',
  shadowOffset: {
    width: 0,
    height: 2,
  },
  shadowOpacity: 0.1,
  shadowRadius: 3,
  elevation: 3,
},
courseItemContent: {
  flex: 1,
},
courseName: {
  fontSize: 16,
  fontWeight: '600',
  color: '#1A202C',
  marginBottom: 4,
},
courseStats: {
  flexDirection: 'row',
  alignItems: 'center',
},
courseStatsText: {
  fontSize: 14,
  color: '#4A5568',
},
});
